export include_path=model/include
export regfile=model/modules/regfile
export ram=model/modules/ram
export fetch=model/modules/fetch
export decoder=model/modules/decoder
export exec=model/modules/exec
export mem=model/modules/mem
export writeback=model/modules/writeback
export top=model/modules/top/top.v
export sim=/app/rv32i_cosim/sim/sim.cpp
export cpp_include=/app/rv32i_cosim/include
export emu=/app/rv32i_cosim/emu
make build
